#!/usr/bin/env python3

"""

Generate an SVG demonstrating OA text justification/orientation mapping.

Code in Public Domain, generated by ChatGPT

Justification/orient strings as defined in Accellera OpenAccess standard
isDrafted is taken to be true, as non-drafted text make no sense

"""

from dataclasses import dataclass

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

FONT_FAMILY = "Arial"
FONT_SIZE = 28
SAMPLE_TEXT = "AgjpQy"

JUSTIFICATIONS = [
    "upperLeft",
    "upperCenter",
    "upperRight",
    "centerLeft",
    "centerCenter",
    "centerRight",
    "lowerLeft",
    "lowerCenter",
    "lowerRight",
]

ORIENTATIONS = [
    "R0",
    "R90",
    "R180",
    "R270",
    "MX",
    "MY",
    "MXR90",
    "MYR90",
]

# ------------------------------------------------------------
# Mapping tables
# ------------------------------------------------------------

VERTICAL_BASELINE = {
    "upper": "hanging",
    "center": "middle",
    "lower": "alphabetic",
}

HORIZONTAL_ANCHOR = {
    "Left": "start",
    "Center": "middle",
    "Right": "end",
}

ROTATED = {
    "R0": False,
    "R90": True,
    "R180": False,
    "R270": True,
    "MX": False,
    "MY": False,
    "MXR90": True,
    "MYR90": True,
}


def split_justify(justify):
    for v in ("upper", "center", "lower"):
        if justify.startswith(v):
            return v, justify[len(v):]
    raise ValueError(justify)


def apply_orientation_mapping(vertical, horizontal, orient):
    """
    Apply the CAD mapping.

    Returns remapped (vertical, horizontal)
    """

    if orient in ("R180", "R270"):
        if vertical == "upper":
            vertical = "lower"
        elif vertical == "lower":
            vertical = "upper"

        if horizontal == "Left":
            horizontal = "Right"
        elif horizontal == "Right":
            horizontal = "Left"

    elif orient in ("MX", "MXR90"):
        if vertical == "upper":
            vertical = "lower"
        elif vertical == "lower":
            vertical = "upper"

    elif orient in ("MY", "MYR90"):
        if horizontal == "Left":
            horizontal = "Right"
        elif horizontal == "Right":
            horizontal = "Left"

    return vertical, horizontal


# ------------------------------------------------------------
# SVG generation
# ------------------------------------------------------------

def oa_text_to_svg(text, justify, orient):
    """
    Returns one SVG <text> element.
    """

    v, h = split_justify(justify)

    v, h = apply_orientation_mapping(v, h, orient)

    baseline = VERTICAL_BASELINE[v]
    anchor = HORIZONTAL_ANCHOR[h]

    attrs = [
        'x="0"',
        'y="0"',
        f'text-anchor="{anchor}"',
        f'dominant-baseline="{baseline}"',
    ]

    if ROTATED[orient]:
        attrs.append('transform="rotate(-90,0,0)"')

    return (
        "<text "
        + " ".join(attrs)
        + f">{text}</text>"
    )


# ------------------------------------------------------------
# Demo SVG
# ------------------------------------------------------------

@dataclass
class Layout:
    margin_x: int = 90
    margin_y: int = 70
    cell_w: int = 170
    cell_h: int = 110


def generate_demo_svg(filename):

    layout = Layout()

    width = layout.margin_x * 2 + len(JUSTIFICATIONS) * layout.cell_w
    height = layout.margin_y * 2 + len(ORIENTATIONS) * layout.cell_h

    svg = []

    svg.append(
        f'''<svg xmlns="http://www.w3.org/2000/svg"
width="{width}"
height="{height}"
viewBox="0 0 {width} {height}">
'''
    )

    svg.append(f"""
<style>
text {{
    font-family:{FONT_FAMILY};
    font-size:{FONT_SIZE}px;
}}

.label {{
    font-size:12px;
    fill:#004080;
}}

.grid {{
    fill:none;
    stroke:#cccccc;
}}

.origin {{
    fill:red;
}}
</style>
""")

    # column titles

    for c, j in enumerate(JUSTIFICATIONS):
        x = layout.margin_x + c * layout.cell_w + layout.cell_w / 2
        y = 20

        svg.append(
            f'<text class="label" x="{x}" y="{y}" text-anchor="middle">{j}</text>'
        )

    # rows

    for r, orient in enumerate(ORIENTATIONS):

        row_y = layout.margin_y + r * layout.cell_h

        svg.append(
            f'<text class="label" x="5" y="{row_y+5}">{orient}</text>'
        )

        for c, justify in enumerate(JUSTIFICATIONS):

            x = layout.margin_x + c * layout.cell_w + layout.cell_w / 2
            y = row_y + layout.cell_h / 2

            svg.append(
                f'''
<g transform="translate({x},{y})">

<rect class="grid"
      x="-70"
      y="-45"
      width="140"
      height="90"/>

<circle class="origin"
        cx="0"
        cy="0"
        r="2.8"/>

{oa_text_to_svg(SAMPLE_TEXT, justify, orient)}

</g>
'''
            )

    svg.append("</svg>")

    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(svg))


# ------------------------------------------------------------

def main():

    outfile = "svg72_mapping.svg"

    generate_demo_svg(outfile)

    print(f"Generated {outfile}")


if __name__ == "__main__":
    main()
